drivers_2025 = [
    "A.J. Allmendinger",
    "Alex Bowman",
    "Austin Cindric",
    "Austin Dillon",
    "Brad Keselowski",
    "Bubba Wallace",
    "Carson Hocevar",
    "Chase Briscoe",
    "Chase Elliott",
    "Chris Buescher",
    "Christopher Bell",
    "Cody Ware",
    "Cole Custer",
    "Daniel Suarez",
    "Denny Hamlin",
    "Erik Jones",
    "Joey Logano",
    "John H. Nemechek",
    "Josh Berry",
    "Justin Haley",
    "Kyle Busch",
    "Kyle Larson",
    "Michael McDowell",
    "Noah Gragson",
    "Ricky Stenhouse Jr",
    "Riley Herbst",
    "Ross Chastain",
    "Ryan Blaney",
    "Ryan Preece",
    "Shane Van Gisbergen",
    "Todd Gilliland",
    "Ty Dillon",
    "Ty Gibbs",
    "Tyler Reddick",
    "William Byron",
"Zane Smith",
]