tracks_similarity = {
    "Atlanta Motor Speedway": ["Daytona International Speedway", "Talladega Superspeedway"],
    # "Auto Club Speedway",
    "Bristol Motor Speedway": ["Dover Motor Speedway"],
    # "Canadian Tire Motorsport Park",
    "Charlotte Motor Speedway": ["Kansas Speedway", "Las Vegas Motor Speedway", "Texas Motor Speedway", "Homestead-Miami Speedway", "Michigan International Speedway"],
    "Charlotte Motor Speedway Road Course": ["Circuit of the Americas", "Chicago Street Course", "Sonoma Raceway", "Watkins Glen International"],
    "Chicago Street Course": ["Circuit of the Americas", "Charlotte Motor Speedway Road Course", "Sonoma Raceway", "Watkins Glen International"],
    # "Chicagoland Speedway",
    "Circuit of the Americas": ["Chicago Street Course", "Charlotte Motor Speedway Road Course", "Sonoma Raceway", "Watkins Glen International"],
    # "Daytona Road Course",
    "Darlington Raceway": ["Homestead-Miami Speedway", "Dover Motor Speedway"],
    "Daytona International Speedway": ["Atlanta Motor Speedway", "Talladega Superspeedway"],
    "Dover Motor Speedway": ["Darlington Raceway", "Bristol Motor Speedway", "Nashville Superspeedway"],
    # "Eldora Speedway",
    "Homestead-Miami Speedway": ["Darlington Raceway", "Charlotte Motor Speedway", "Kansas Speedway", "Las Vegas Motor Speedway", "Texas Motor Speedway"],
    "Indianapolis Motor Speedway": ["Pocono Raceway", "Michigan International Speedway"],
    # "Indianapolis Motor Speedway Road Course",
    "Iowa Speedway": ["Richmond Raceway", "New Hampshire Motor Speedway", "Phoenix Raceway"],
    "Kansas Speedway": ["Las Vegas Motor Speedway", "Michigan International Speedway", "Texas Motor Speedway", "Homestead-Miami Speedway", "Charlotte Motor Speedway"],
    # "Kentucky Speedway",
    # "Knoxville Raceway",
    "Las Vegas Motor Speedway": ["Michigan International Speedway", "Texas Motor Speedway", "Kansas Speedway", "Charlotte Motor Speedway"],
    # "Los Angeles Memorial Coliseum",
    # "Lucas Oil Indianapolis Raceway",
    "Martinsville Speedway": ["New Hampshire Motor Speedway", "North Wilkesboro Speedway"],
    "Michigan International Speedway": ["Las Vegas Motor Speedway", "Kansas Speedway", "Texas Motor Speedway", "Homestead-Miami Speedway", "Charlotte Motor Speedway"],
    # "Mid-Ohio Sports Car Course",
    # "Milwaukee Mile Speedway",
    "Nashville Superspeedway": ["Dover Motor Speedway"],
    "New Hampshire Motor Speedway": ["Richmond Raceway",  "Phoenix Raceway",  "Martinsville Speedway", "Iowa Speedway", "North Wilkesboro Speedway", "World Wide Technology Raceway at Gateway"],
    "North Wilkesboro Speedway": ["Richmond Raceway",  "Phoenix Raceway",  "Martinsville Speedway", "World Wide Technology Raceway at Gateway"],
    "Phoenix Raceway": ["Richmond Raceway",  "New Hampshire Motor Speedway", "World Wide Technology Raceway at Gateway"],
    "Pocono Raceway": ["Indianapolis Motor Speedway", "Michigan International Speedway"],
    # "Portland International Raceway",
    "Richmond Raceway": ["New Hampshire Motor Speedway",  "Phoenix Raceway",  "Martinsville Speedway", "Iowa Speedway", "World Wide Technology Raceway at Gateway"],
    # "Road America",
    # "Sebring Raceway",
    "Sonoma Raceway": ["Circuit of the Americas", "Charlotte Motor Speedway Road Course", "Chicago Street Course", "Watkins Glen International"],
    "Talladega Superspeedway": ["Atlanta Motor Speedway", "Daytona International Speedway"],
    "Texas Motor Speedway": ["Las Vegas Motor Speedway", "Michigan International Speedway", "Kansas Speedway", "Homestead-Miami Speedway", "Charlotte Motor Speedway"],
    "Watkins Glen International": ["Circuit of the Americas", "Charlotte Motor Speedway Road Course", "Chicago Street Course", "Sonoma Raceway"],
    "World Wide Technology Raceway at Gateway": ["New Hampshire Motor Speedway", "Richmond Raceway", "Phoenix Raceway"],
}