owners_to_teams = {
    'Joe Gibbs': 'Joe Gibbs Racing',
    'Stewart Haas Racing': 'Stewart-Haas Racing',
    'Rick Hendrick': 'Hendrick Motorsports',
    'Jack Roush': 'RFK Racing',
    '23XI Racing': '23XI Racing',
    'JTG-Daugherty Racing': 'JTG Daugherty Racing',
    'Trackhouse Racing': 'Trackhouse Racing',
    'Wood Brothers': 'Wood Brothers Racing',
    'Spire Motorsports': 'Spire Motorsports',
    'Roger Penske': 'Team Penske',
    'Matthew Kaulig': 'Kaulig Racing',
    'Rick Ware': 'Rick Ware Racing',
    'Richard Childress': 'Richard Childress Racing',
    'Bob Jenkins': 'Front Row Motorsports',
    'Legacy Motor Club': 'Legacy Motor Club',
    'Beard Motorsports': 'Beard Motorsports',
    'B.J. McLeod': 'Live Fast Motorsports',
    'TMT Racing': '23XI Racing',
    'Carl Long': 'Power Source',
    'Johnathan Cohen': 'NY Racing Team',
    'HYAK Motorsports': 'HYAK Motorsports',
    'Gene Haas': 'Haas Factory Team',
    'Petty GMS Motorsports': 'Petty GMS Motorsports',
    'Team Hezeberg': 'Team Hezeberg',
    'Team AmeriVet': 'Team Amerivet',
    'JR Motorsports': 'JR Motorsports',
}